import { ChecklistCategory, ActivityItem } from "@/types/checklist";

export const defaultCategories: ChecklistCategory[] = [
  {
    id: "fecha-tramites",
    emoji: "📅",
    title: "Fecha y trámites",
    detailFields: [
      { label: "Fecha", placeholder: "Ej: 15 de junio 2026" },
      { label: "Hora", placeholder: "Ej: 4:00 PM" },
      { label: "Estado", placeholder: "Ej: Pendiente / Confirmado" },
    ],
    items: [
      { id: "ft-1", label: "Definir fecha definitiva", checked: false },
      { id: "ft-2", label: "Reservar el lugar", checked: false },
      { id: "ft-3", label: "Definir horario", checked: false },
      { id: "ft-4", label: "Trámite de matrimonio civil (si aplica)", checked: false },
      { id: "ft-5", label: "Charlas prematrimoniales con el pastor", checked: false },
      { id: "ft-6", label: "Definir los versículos bíblicos", checked: false },
      { id: "ft-7", label: "Escribir los votos", checked: false },
    ],
  },
  {
    id: "lugar",
    emoji: "🌿",
    title: "Lugar",
    detailFields: [
      { label: "Nombre", placeholder: "Nombre del lugar" },
      { label: "Dirección", placeholder: "Dirección completa" },
      { label: "Teléfono", placeholder: "Número de contacto" },
      { label: "Contacto", placeholder: "Nombre del contacto" },
      { label: "Precio", placeholder: "Presupuesto / costo" },
      { label: "Capacidad", placeholder: "Máximo de invitados" },
    ],
    items: [
      { id: "lu-1", label: "Lugar para ceremonia y recepción", checked: false },
      { id: "lu-2", label: "Plan B por lluvia", checked: false },
      { id: "lu-3", label: "Sillas", checked: false },
      { id: "lu-4", label: "Mesas", checked: false },
      { id: "lu-5", label: "Manteles", checked: false },
      { id: "lu-6", label: "Carpas (si son necesarias)", checked: false },
      { id: "lu-7", label: "Baños suficientes", checked: false },
      { id: "lu-8", label: "Parqueadero", checked: false },
    ],
  },
  {
    id: "decoracion",
    emoji: "🌸",
    title: "Decoración",
    detailFields: [
      { label: "Proveedor", placeholder: "Tienda / persona" },
      { label: "Precio", placeholder: "Costo" },
      { label: "Color", placeholder: "Color elegido" },
      { label: "Material", placeholder: "Tipo de material" },
      { label: "Donde comprar", placeholder: "Enlace o dirección" },
    ],
    items: [
      { id: "de-1", label: "Arco para la ceremonia", checked: false },
      { id: "de-2", label: "Cruz detrás del arco", checked: false },
      { id: "de-3", label: "Flores", checked: false },
      { id: "de-4", label: "Camino de la novia", checked: false },
      { id: "de-5", label: "Decoración de la mesa principal", checked: false },
      { id: "de-6", label: "Decoración de entrada", checked: false },
      { id: "de-7", label: "Centros de mesa (recuerdos para los invitados)", checked: false },
      { id: "de-8", label: "Iluminación o velas", checked: false },
    ],
  },
  {
    id: "novia",
    emoji: "👰",
    title: "Novia",
    detailFields: [
      { label: "Tienda", placeholder: "Donde se compra" },
      { label: "Precio", placeholder: "Costo" },
      { label: "Color", placeholder: "Color elegido" },
      { label: "Talla", placeholder: "Talla" },
      { label: "Fecha de entrega", placeholder: "Cuando lo entregan" },
      { label: "Estado", placeholder: "Pedido / Entregado / Ajustado" },
    ],
    items: [
      { id: "no-1", label: "Vestido", checked: false },
      { id: "no-2", label: "Zapatos", checked: false },
      { id: "no-3", label: "Velo", checked: false },
      { id: "no-4", label: "Accesorios", checked: false },
      { id: "no-5", label: "Ramo", checked: false },
      { id: "no-6", label: "Maquillaje", checked: false },
      { id: "no-7", label: "Peinado", checked: false },
    ],
  },
  {
    id: "novio",
    emoji: "🤵",
    title: "Novio",
    detailFields: [
      { label: "Tienda", placeholder: "Donde se compra" },
      { label: "Precio", placeholder: "Costo" },
      { label: "Color", placeholder: "Color elegido" },
      { label: "Talla", placeholder: "Talla" },
      { label: "Estado", placeholder: "Pedido / Entregado" },
    ],
    items: [
      { id: "nv-1", label: "Traje", checked: false },
      { id: "nv-2", label: "Camisa", checked: false },
      { id: "nv-3", label: "Corbata o corbatín", checked: false },
      { id: "nv-4", label: "Zapatos", checked: false },
      { id: "nv-5", label: "Cinturón", checked: false },
      { id: "nv-6", label: "Flor del traje (boutonnière)", checked: false },
    ],
  },
  {
    id: "anillos",
    emoji: "💍",
    title: "Anillos",
    detailFields: [
      { label: "Joyería", placeholder: "Nombre de la joyería" },
      { label: "Precio", placeholder: "Costo" },
      { label: "Material", placeholder: "Oro, plata, etc." },
      { label: "Talla", placeholder: "Talla del anillo" },
      { label: "Fecha de entrega", placeholder: "Cuando los entregan" },
    ],
    items: [
      { id: "an-1", label: "Anillos", checked: false },
      { id: "an-2", label: "Caja para los anillos", checked: false },
    ],
  },
  {
    id: "musica",
    emoji: "🎵",
    title: "Música",
    detailFields: [
      { label: "Canción / Título", placeholder: "Nombre de la canción" },
      { label: "Artista", placeholder: "Nombre del artista" },
      { label: "Enlace", placeholder: "URL de Spotify, YouTube, etc." },
      { label: "Proveedor de sonido", placeholder: "Contacto del proveedor" },
    ],
    items: [
      { id: "mu-1", label: "Playlist de ceremonia", checked: false },
      { id: "mu-2", label: "Playlist de recepción", checked: false },
      { id: "mu-3", label: "Equipo de sonido", checked: false },
      { id: "mu-4", label: "Micrófonos", checked: false },
      { id: "mu-5", label: "Persona encargada de la música", checked: false },
      { id: "mu-6", label: "Canción de entrada de la novia", checked: false },
      { id: "mu-7", label: "Canción del primer baile", checked: false },
      { id: "mu-8", label: "Canción del baile padre-hija", checked: false },
    ],
  },
  {
    id: "foto-video",
    emoji: "📸",
    title: "Fotografía y video",
    detailFields: [
      { label: "Nombre", placeholder: "Nombre del profesional" },
      { label: "Teléfono", placeholder: "Número de contacto" },
      { label: "Precio", placeholder: "Costo del servicio" },
      { label: "Paquete", placeholder: "Qué incluye" },
      { label: "Horario", placeholder: "Desde - Hasta" },
    ],
    items: [
      { id: "fv-1", label: "Fotógrafo", checked: false },
      { id: "fv-2", label: "Videógrafo (opcional)", checked: false },
      { id: "fv-3", label: "Lista de fotografías importantes", checked: false },
    ],
  },
  {
    id: "cena",
    emoji: "🍽️",
    title: "Cena",
    detailFields: [
      { label: "Proveedor", placeholder: "Nombre del catering" },
      { label: "Menú", placeholder: "Platos incluidos" },
      { label: "Precio por persona", placeholder: "Costo por plato" },
      { label: "Contacto", placeholder: "Teléfono / email" },
      { label: "Restricciones", placeholder: "Alergias, vegetariano, etc." },
    ],
    items: [
      { id: "ce-1", label: "Catering", checked: false },
      { id: "ce-2", label: "Definir menú", checked: false },
      { id: "ce-3", label: "Bebidas", checked: false },
      { id: "ce-4", label: "Restricciones alimentarias y alergias", checked: false },
      { id: "ce-5", label: "Vajilla", checked: false },
      { id: "ce-6", label: "Cubiertos", checked: false },
      { id: "ce-7", label: "Meseros", checked: false },
    ],
  },
  {
    id: "pastel",
    emoji: "🎂",
    title: "Pastel",
    detailFields: [
      { label: "Pastelería", placeholder: "Nombre de la pastelería" },
      { label: "Sabor", placeholder: "Sabor del pastel" },
      { label: "Precio", placeholder: "Costo" },
      { label: "Capas", placeholder: "Número de niveles" },
      { label: "Diseño", placeholder: "Descripción o imagen de referencia" },
      { label: "Fecha de entrega", placeholder: "Cuando lo entregan" },
    ],
    items: [
      { id: "pa-1", label: "Pastel", checked: false },
      { id: "pa-2", label: "Base", checked: false },
      { id: "pa-3", label: "Cuchillo", checked: false },
      { id: "pa-4", label: "Espátula", checked: false },
    ],
  },
  {
    id: "brindis",
    emoji: "🥂",
    title: "Brindis",
    detailFields: [
      { label: "Tipo de bebida", placeholder: "Champagne, vino, etc." },
      { label: "Cantidad", placeholder: "Número de copas" },
      { label: "Precio", placeholder: "Costo" },
      { label: "Donde comprar", placeholder: "Tienda / enlace" },
    ],
    items: [
      { id: "br-1", label: "Copas", checked: false },
      { id: "br-2", label: "Bebida para brindar", checked: false },
    ],
  },
  {
    id: "recuerdos",
    emoji: "🎁",
    title: "Recuerdos",
    detailFields: [
      { label: "Descripción", placeholder: "Qué son / cómo se ven" },
      { label: "Proveedor", placeholder: "Donde se compran" },
      { label: "Precio unitario", placeholder: "Costo por unidad" },
      { label: "Cantidad", placeholder: "Número de invitados" },
      { label: "Donde comprar", placeholder: "Enlace o dirección" },
    ],
    items: [
      { id: "re-1", label: "Centros de mesa / recuerdos para los invitados", checked: false },
    ],
  },
  {
    id: "invitaciones",
    emoji: "💌",
    title: "Invitaciones",
    detailFields: [
      { label: "Diseñador", placeholder: "Quién las diseña" },
      { label: "Formato", placeholder: "Física / Digital" },
      { label: "Cantidad", placeholder: "Número de invitaciones" },
      { label: "Precio", placeholder: "Costo total" },
      { label: "Enlace digital", placeholder: "URL si es digital" },
    ],
    items: [
      { id: "in-1", label: "Diseño", checked: false },
      { id: "in-2", label: "Confirmación de asistencia (RSVP)", checked: false },
      { id: "in-3", label: "Preguntar por alergias o restricciones alimentarias", checked: false },
      { id: "in-4", label: "Preguntar si hay alimentos que prefieran evitar", checked: false },
      { id: "in-5", label: "Consultar si les gustaría espacio de baile libre", checked: false },
      { id: "in-6", label: "Compartir ubicación del evento", checked: false },
      { id: "in-7", label: "Enviar recordatorio una semana antes", checked: false },
    ],
  },
  {
    id: "actividades",
    emoji: "🎲",
    title: "Actividades",
    detailFields: [
      { label: "Descripción", placeholder: "En qué consiste" },
      { label: "Material", placeholder: "Qué se necesita" },
      { label: "Cantidad", placeholder: "Unidades" },
      { label: "Precio", placeholder: "Costo" },
      { label: "Donde comprar", placeholder: "Tienda / enlace" },
    ],
    items: [
      { id: "ac-1", label: "Material para las actividades", checked: false },
      { id: "ac-2", label: "Premios (si aplica)", checked: false },
      { id: "ac-3", label: "Libro de firmas", checked: false },
      { id: "ac-4", label: "Caja para cartas, consejos y bendiciones", checked: false },
      { id: "ac-5", label: "Caja para sobres con dinero", checked: false },
    ],
  },
  {
    id: "organizacion",
    emoji: "🪑",
    title: "Organización",
    detailFields: [
      { label: "Detalle", placeholder: "Descripción / instrucciones" },
      { label: "Responsable", placeholder: "Quién se encarga" },
    ],
    items: [
      { id: "or-1", label: "Distribución de mesas", checked: false },
      { id: "or-2", label: "Identificación de mesas", checked: false },
      { id: "or-3", label: "Lista definitiva de confirmados", checked: false },
    ],
  },
  {
    id: "responsables",
    emoji: "👥",
    title: "Responsables",
    detailFields: [
      { label: "Nombre", placeholder: "Nombre de la persona" },
      { label: "Teléfono", placeholder: "Número de contacto" },
      { label: "Rol", placeholder: "Qué le toca" },
      { label: "Horario", placeholder: "Cuándo necesita estar" },
    ],
    items: [
      { id: "re-1", label: "Coordinador del evento", checked: false },
      { id: "re-2", label: "Encargado de la música", checked: false },
      { id: "re-3", label: "Encargado de recibir invitados", checked: false },
      { id: "re-4", label: "Persona que coordine las fotografías", checked: false },
      { id: "re-5", label: "Persona que dirija las actividades", checked: false },
    ],
  },
  {
    id: "ceremonia",
    emoji: "🎤",
    title: "Ceremonia",
    detailFields: [
      { label: "Detalle", placeholder: "Descripción / notas" },
      { label: "Responsable", placeholder: "Quién lo lleva" },
    ],
    items: [
      { id: "ce-1", label: "Biblia", checked: false },
      { id: "ce-2", label: "Micrófono para el pastor", checked: false },
      { id: "ce-3", label: "Mesa para la ceremonia (si es necesaria)", checked: false },
      { id: "ce-4", label: "Sillas para los padres", checked: false },
    ],
  },
  {
    id: "transporte",
    emoji: "🚗",
    title: "Transporte",
    detailFields: [
      { label: "Tipo", placeholder: "Carro, bus, etc." },
      { label: "Contacto", placeholder: "Nombre / teléfono" },
      { label: "Precio", placeholder: "Costo" },
      { label: "Horario", placeholder: "Hora de recogida" },
      { label: "Ruta", placeholder: "Puntos de paso" },
    ],
    items: [
      { id: "tr-1", label: "Transporte de la novia", checked: false },
      { id: "tr-2", label: "Transporte del novio", checked: false },
      { id: "tr-3", label: "Transporte para familiares (si aplica)", checked: false },
    ],
  },
  {
    id: "emergencias",
    emoji: "🩹",
    title: "Emergencias",
    detailFields: [
      { label: "Cantidad", placeholder: "Unidades" },
      { label: "Ubicación", placeholder: "Dónde se guarda" },
      { label: "Estado", placeholder: "Comprado / Pendiente" },
    ],
    items: [
      { id: "em-1", label: "Botiquín", checked: false },
      { id: "em-2", label: "Agua", checked: false },
      { id: "em-3", label: "Paraguas", checked: false },
      { id: "em-4", label: "Kit de costura", checked: false },
      { id: "em-5", label: "Analgésicos", checked: false },
      { id: "em-6", label: "Pañuelos", checked: false },
      { id: "em-7", label: "Cargadores", checked: false },
      { id: "em-8", label: "Extensión eléctrica", checked: false },
      { id: "em-9", label: "Cinta transparente", checked: false },
      { id: "em-10", label: "Tijeras", checked: false },
    ],
  },
  {
    id: "para-ustedes",
    emoji: "❤️",
    title: "Para ustedes",
    detailFields: [
      { label: "Nota", placeholder: "Algo que recordar" },
      { label: "Estado", placeholder: "Pendiente / Hecho" },
    ],
    items: [
      { id: "pu-1", label: "Escribir los votos", checked: false },
      { id: "pu-2", label: "Ensayar la ceremonia", checked: false },
      { id: "pu-3", label: "Ensayar el primer baile", checked: false },
      { id: "pu-4", label: "Tener un momento de oración antes de comenzar", checked: false },
      { id: "pu-5", label: "Designar una persona que resuelva inconvenientes", checked: false },
    ],
  },
  {
    id: "fotos-importantes",
    emoji: "📷",
    title: "Fotografías importantes",
    detailFields: [
      { label: "Personas", placeholder: "Quiénes aparecen" },
      { label: "Lugar", placeholder: "Dónde se toma" },
      { label: "Referencia", placeholder: "Enlace o descripción" },
    ],
    items: [
      { id: "fi-1", label: "Novios", checked: false },
      { id: "fi-2", label: "Padres", checked: false },
      { id: "fi-3", label: "Hermanos", checked: false },
      { id: "fi-4", label: "Abuelos", checked: false },
      { id: "fi-5", label: "Familia completa", checked: false },
      { id: "fi-6", label: "Pastor", checked: false },
      { id: "fi-7", label: "Corte del pastel", checked: false },
      { id: "fi-8", label: "Brindis", checked: false },
      { id: "fi-9", label: "Bailes", checked: false },
      { id: "fi-10", label: "Actividades", checked: false },
      { id: "fi-11", label: "Foto grupal con todos los invitados", checked: false },
    ],
  },
];

export const activityItems: ActivityItem[] = [
  { id: "a-green-1", label: "Definir fecha", priority: "green" },
  { id: "a-green-2", label: "Elegir versículos bíblicos", priority: "green" },
  { id: "a-green-3", label: "Escribir votos (cada uno)", priority: "green" },
  { id: "a-green-4", label: "Diseñar invitaciones", priority: "green" },
  { id: "a-green-5", label: "Enviar invitaciones", priority: "green" },
  { id: "a-green-6", label: "Confirmar asistencia (RSVP)", priority: "green" },
  { id: "a-green-7", label: "Elegir fotógrafo", priority: "green" },
  { id: "a-green-8", label: "Contratar sonido", priority: "green" },
  { id: "a-green-9", label: "Crear playlist de ceremonia", priority: "green" },
  { id: "a-green-10", label: "Crear playlist de recepción", priority: "green" },
  { id: "a-green-11", label: "Planear las actividades", priority: "green" },
  { id: "a-green-12", label: "Comprar las dos cajas (cartas y sobres)", priority: "green" },
  { id: "a-green-13", label: "Comprar libro de firmas", priority: "green" },
  { id: "a-green-14", label: "Definir distribución de mesas", priority: "green" },
  { id: "a-green-15", label: "Elaborar lista de fotografías", priority: "green" },
  { id: "a-green-16", label: "Asignar responsables", priority: "green" },
  { id: "a-green-17", label: "Comprar zapatos del novio", priority: "green" },
  { id: "a-green-18", label: "Preparar el kit de emergencia", priority: "green" },

  { id: "a-yellow-1", label: "Visitar y reservar el lugar", priority: "yellow" },
  { id: "a-yellow-2", label: "Elegir decoración", priority: "yellow" },
  { id: "a-yellow-3", label: "Elegir flores", priority: "yellow" },
  { id: "a-yellow-4", label: "Comprar el traje del novio", priority: "yellow" },
  { id: "a-yellow-5", label: "Elegir el catering", priority: "yellow" },
  { id: "a-yellow-6", label: "Elegir el pastel", priority: "yellow" },
  { id: "a-yellow-7", label: "Degustación del pastel", priority: "yellow" },
  { id: "a-yellow-8", label: "Elegir los recuerdos (centros de mesa)", priority: "yellow" },
  { id: "a-yellow-9", label: "Comprar accesorios de la novia", priority: "yellow" },

  { id: "a-red-1", label: "Charlas prematrimoniales", priority: "red" },
  { id: "a-red-2", label: "Trámite de matrimonio civil", priority: "red" },
  { id: "a-red-3", label: "Elegir el vestido de novia", priority: "red" },
  { id: "a-red-4", label: "Ajustes del vestido", priority: "red" },
  { id: "a-red-5", label: "Comprar los anillos", priority: "red" },
  { id: "a-red-6", label: "Degustación del menú", priority: "red" },
  { id: "a-red-7", label: "Ensayar el primer baile", priority: "red" },
  { id: "a-red-8", label: "Ensayo general de la ceremonia", priority: "red" },
];
